kind: pipeline
type: docker
name: build
steps:
- name: 编译文件
  image: node:18.13.0
  pull: if-not-exists # always never
  commands:
    - node -v
    - npm -v
    - yarn --version
    - yarn config set cache-folder .yarn-cache
    - yarn install
    - yarn run build

- name: 同步文件
  image: drillster/drone-rsync
  settings:
    user: pms
    key:
      from_secret: ssh_key
    hosts:
      - 192.168.11.2
    # 来源项目目录
    source: ./dist/*
    # 目标服务器目录
    target: /www/wwwroot/www
    script:
      - cd /www/wwwroot/www
      - ls